# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: commons.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


class Color(betterproto.Enum):
    OFF = 0
    GREEN = 1
    ORANGE = 2
    GREEN_ORANGE = 3
    RED = 4
    RED_GREEN = 5
    RED_ORANGE = 6
    RED_ORANGE_GREEN = 7


@dataclass(eq=False, repr=False)
class JsonContent(betterproto.Message):
    """
    The JsonContent message is used as a field in other messages to hold dictionary/Json data.
    Notes for Python:
    Serialization/deserialization of am.commons.JsonContent fields happens transparently
    (no need to build the JsonContent message, just set the field with the dictionary).

    Supported betterproto methods: __bytes__, parse, to_dict, from_dict
    """

    content: bytes = betterproto.bytes_field(1)
