# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tests.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import Dict, Optional, Union

import betterproto

from .. import commons as _commons__


@dataclass(eq=False, repr=False)
class TestMessage(betterproto.Message):
    content: str = betterproto.string_field(10)
    number: int = betterproto.int64_field(20)
    detail: Optional[str] = betterproto.string_field(30, optional=True)
    options: Optional[Union["_commons__.JsonContent", Dict]] = betterproto.message_field(
        40, optional=True
    )
    color: Optional["_commons__.Color"] = betterproto.enum_field(50, optional=True)


#######################################################
# Dynamically added by post_compile.py

from . import tasks  # noqa
