# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tasks.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import Dict, List, Optional, Union

import betterproto

from ... import commons as __commons__


@dataclass(eq=False, repr=False)
class TaskMessage(betterproto.Message):
    content: str = betterproto.string_field(10)
    bbox: List[float] = betterproto.float_field(30)
    options: Optional[Union["__commons__.JsonContent", Dict]] = betterproto.message_field(
        40, optional=True
    )
